#Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/unittestpy
    steps:
   #1 Obtain repo from Github
     - checkout
  #2 Create a virtual environment and install dependencies
     - run:
        name: install dependencies
        command: |
         python3 -m venv venv
         . venv/bin/activate
         /home/circleci/unittestpy/venv/bin/python3 -m pip install --upgrade pip
         mkdir -p /home/circleci/unittestpy/test_results
         pip install pipreqs
         pipreqs /home/circleci/unittestpy/venv/bin/assign5_unittest.py
  #3 Run coding convention software plus tester.
     - run:
        name: run tests
        command: |
         . venv/bin/activate
         python3 -m unittest assign5_unittest.py
     - store_test_results:
        path: test-results 
     - store_artifacts:
        path: test-results
